### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Arlion** [ngerakines/commitment#153]
So thanks guys.. I have used this service for my company to submit code. Now and forever there will be "Shit code" as one of my commits. 

I like the random commits that are snarky and funny. Could we have a clean version.. so I can keep my job and continue shitposting?

Thanks.

**Comment by ngerakines** [comment]
Is this a joke?

**Comment by Arlion** [comment]
Sadly no.

**Comment by ngerakines** [comment]
I'm not really sure what to tell you. Pay better attention to the things you use?
