### ISSUE TITLE
Generate whatthecommit messages locally w/o web server?

### ISSUE THREAD

**Issue by TinaRussell** [ngerakines/commitment#192]
I pull messages from whatthecommit.com all the time in scripts meant to sync my private git repos, because I’m the only one who will see those commits and this makes them freaking hilarious. I’m wondering if the code to generate them could be run locally, without using the Tornado web application server (or whatever it is). I’m sure this would save on your bandwidth :sweat_smile:

**Comment by ShanTulshi** [comment]
You should be able to use `shuf` to pick a random line out of the `commit_messages.txt` file as shown [here](https://stackoverflow.com/questions/448005/whats-an-easy-way-to-read-random-line-from-a-file-in-unix-command-line):
```bash
shuf -n 1 commit_messages.txt
```

On MacOS, this is available as `gshuf` through `brew install coreutils`.

For Powershell, my (probably not great) solution:
```powershell
Get-Content commit-messages.txt | Select -Index (Get-Random (Get-Content commit_messages.txt).Count)
```

**Comment by TinaRussell** [comment]
Okay! (I’m on Linux, BTW.) How would I get it to interpret forms like `XNAMEX`, `XUPPERNAMEX`, `XLOWERNAMEX`, `XNUMX`, `XNUM30X`, `XNUM2,5X` etc. correctly?

**Comment by ShanTulshi** [comment]
I'm not sure whether the easiest way to do that is with a bash find-replace or by refactoring the application so it can be run locally, to be quite honest.

**Comment by TinaRussell** [comment]
All right, thanks! Feel free to mark this as a feature request.

**Comment by Gaardsholt** [comment]
If you are using vscode, you could use my extension :)
https://github.com/Gaardsholt/vscode-whatthecommit

Offline version will come later ;)

**Comment by janraasch** [comment]
My npm package does the trick as well: https://github.com/janraasch/javascript-commitment

And there's a package for `Atom`: https://atom.io/packages/commitment

Both work **offline**.

**Comment by ngerakines** [comment]
There are some great alternatives, so I'm going to close this.
