### ISSUE TITLE
Make whatthecommit always use https

### ISSUE THREAD

**Issue by Andre601** [ngerakines/commitment#205]
I use the whatthecommit site for my own Discord bot.
When I first connected to the site, it defaulted to HTTP, so I thought it wouldn't have HTTPS available.

However, this caused my bot to throw UnknownHostExceptions at random moments, when connecting to the site, to receive a random commit,
I later found out (Just now to be more exact) that the site actually offers HTTPS connections and using that seems to have solved my issue.

Since connections don't default to HTTPS, I would suggest to actually make it move to HTTPS when connecting over HTTP since this is A) Saver in general, B) More trustworthy and C) most likely prevents issues as I had.
I would also recommend to show and use the default HTTPS link in the readme.

If there are any reasons, why the site shouldn't default to HTTPS I would be glad to know those.

I'm sorry when this was the wrong place for those suggestions, but I didn't find any better place.

**Comment by Plloi** [comment]
While i do agree that HTTPS is all around better for something like this it would have prevented your error. 
UnknownHostExceptions are thrown when a host can't be looked up, your issue was/is likely DNS.

**Comment by ngerakines** [comment]
Agreed, however unless this project gets a few monthly sponsors, this project is going to sit in the free tier of Heroku hosting.

**Comment by Andre601** [comment]
That explains a lot
