### ISSUE TITLE
Has the whatthecommit.com service stopped working?

### ISSUE THREAD

**Issue by LiangJianyi** [ngerakines/commitment#243]
I execute `print "$(curl -s http://whatthecommit.com/index.txt)"` without returning any results. I try open http://whatthecommit.com/index.txt in browser then the requested URL could not be retrieved
<img width="1240" alt="Screen Shot 2021-09-25 at 19 19 05" src="https://user-images.githubusercontent.com/23691171/134769570-a7ed5961-4c2b-4408-8283-c36f86c6290c.png">
.

**Comment by Smithienious** [comment]
It is working. You can close this issue.

**Comment by He4eT** [comment]
You should replace `http` with `https` in your code:

```
print "$(curl -s http://whatthecommit.com/index.txt)"
```
