### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by PHPirates** [ngerakines/commitment#253]
@ngerakines Seems like the site is not working, I only see the "Welcome to nginx" message?

**Comment by ngerakines** [comment]
https://thegem.city/@nick/109280480045871636

I started the migration of whatthecommit.com out of Heroku. It started on Friday with disabling DNSSEC which needed at least 24 hours and then the migration of the NS servers which needed another 24 hours. It'll be back up soon.

I'll leave this issue open until it is fully back and operational, but also check that post for updates.

**Comment by ngerakines** [comment]
Looks like everything is resolving consistently.
