### ISSUE TITLE
whatthecommit.com can't use in China

### ISSUE THREAD

**Issue by GBEYOND0613** [ngerakines/commitment#261]
When I use the command `curl -s https://whatthecommit.com/index.txt`, it return `403 Forbidden`.

And this also occurs when accessing the site with a browser. Both `http` and `https`.

this is the return context:

``` html
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
````

**Comment by ngerakines** [comment]
Working as intended
