### ISSUE TITLE
Add to commit-msg hook as prank

### ISSUE THREAD

**Issue by SamWhited** [ngerakines/commitment#69]
This makes a decent prank. By sticking something like:

```bash
curl -s https://raw.github.com/ngerakines/commitment/master/commit_messages.txt | shuf -n1 > "$1" | sed s/XUPPERNAMEX/PERSONSNAME/g
```

in the `.git/hooks/commit-msg` hook file and making it executable. Maybe add a `commit-msg.sample` file to the repo w/ something like this? It can be made more cross platform by using `sort -R | head -n1` or similar instead of GNU shuf.

**Comment by netojoaobatista** [comment]
`git config --global alias.rci '!git commit -m "`curl -s http://whatthecommit.com/index.txt`"'`

**Comment by shubhamchaudhary** [comment]
I use:
```
git config --global alias.yolo '!git commit -m "$(curl -s whatthecommit.com/index.txt)"'
```

**Comment by ngerakines** [comment]
What I suggest is that someone forks the project and adds this information to the README.
